export const themes = {
  default: {
    background: "bg-[#f4f4f8]",
    text: "text-[#333333]",
    card: "bg-white",
    cardBorder: "border-[#e0e0e4]",
    cardText: "text-[#4a4a4a]",
    button: "bg-[#5a5a5a] hover:bg-[#4a4a4a] text-white",
    input: "bg-white border-[#d1d1d5] text-[#333333]",
    userMessage: "bg-blue-500 text-white",
    assistantMessage: "bg-gray-100 text-gray-900",
  },
  light: {
    background: 'bg-white',
    text: 'text-gray-900',
    card: 'bg-white',
    cardBorder: 'border-gray-200',
    cardText: 'text-gray-900',
    button: 'bg-blue-500 hover:bg-blue-600 text-white',
    input: 'bg-white border-gray-200',
    messageBg: 'bg-gray-100',
    messageText: 'text-gray-900',
    userMessage: "bg-blue-500 text-white",
    assistantMessage: "bg-gray-100 text-gray-900",
  },
  dark: {
    background: 'bg-gray-900',
    text: 'text-gray-100',
    card: 'bg-gray-800',
    cardBorder: 'border-gray-700',
    cardText: 'text-gray-100',
    button: 'bg-blue-600 hover:bg-blue-700 text-white',
    input: 'bg-gray-700 border-gray-600',
    messageBg: 'bg-gray-800',
    messageText: 'text-gray-100',
    userMessage: "bg-blue-600 text-white",
    assistantMessage: "bg-gray-700 text-gray-100",
  },
  nature: {
    background: "bg-green-50",
    text: "text-green-900",
    card: "bg-white",
    cardBorder: "border-green-200",
    cardText: "text-green-800",
    button: "bg-green-600 hover:bg-green-700 text-white",
    input: "bg-white border-green-300",
    userMessage: "bg-green-600 text-white",
    assistantMessage: "bg-green-100 text-green-900",
  },
};
