export const themes = {
  default: {
    background: "bg-[#f4f4f8]",
    text: "text-[#333333]",
    card: "bg-white",
    cardBorder: "border-[#e0e0e4]",
    cardText: "text-[#4a4a4a]",
    button: "bg-[#5a5a5a] hover:bg-[#4a4a4a] text-white",
    input: "bg-white border-[#d1d1d5] text-[#333333]",
  },
  light: {
    background: "bg-[#fff5e6]",
    text: "text-[#4a3f35]",
    card: "bg-[#fffaf0]",
    cardBorder: "border-[#e6d9c6]",
    cardText: "text-[#6b5b4f]",
    button: "bg-[#e67e22] hover:bg-[#d35400] text-white",
    input: "bg-white border-[#e6d9c6] text-[#4a3f35]",
  },
  dark: {
    background: "bg-[#1e1e1e]",
    text: "text-[#d4d4d4]",
    card: "bg-[#252526]",
    cardBorder: "border-[#3e3e42]",
    cardText: "text-[#9cdcfe]",
    button: "bg-[#0e639c] hover:bg-[#1177bb] text-white",
    input: "bg-[#3c3c3c] border-[#3c3c3c] text-[#cccccc]",
  },
  nature: {
    background: "bg-green-50",
    text: "text-green-900",
    card: "bg-white",
    cardBorder: "border-green-200",
    cardText: "text-green-800",
    button: "bg-green-600 hover:bg-green-700 text-white",
    input: "bg-white border-green-300",
  },
};
